import { AppContextProvider } from "@/context/AppContext";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = cookies().get("theme");
  return (
    <html lang="en" className="fill-orange">
      <body className={`${inter.className}`}>
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
